addr: localhost
port: 1111
ocr_exe_path: res\PaddleOCR-json_v1.4.0\PaddleOCR-json.exe
min_processors: 4
max_processors: 20
queue_size: 100
scale_threshold: 75
degrade_threshold: 25
idle_timeout: 5m0s
warm_up_count: 2
shutdown_timeout: 30s
log_file_path: ocr_server.log
log_max_size: 100
log_max_backups: 3
log_max_age: 28
log_compress: false
threshold_mode: 0
threshold_value: 100
